{% set name = "python3-openid" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 628d365d687e12da12d02c6691170f4451db28d6d68d050007e4a40065868502

build:
  skip: True  # [py2k]
  number: 1004
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - defusedxml  # [py>=34]
    - defusedxml <=0.4.1  # [py<34]

test:
  imports:
    - openid
    - openid.consumer
    - openid.extensions
    - openid.extensions.draft
    - openid.server
    - openid.store
    - openid.yadis

about:
  home: http://github.com/necaris/python3-openid
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: 'OpenID support for modern servers and consumers.'
  dev_url: http://github.com/necaris/python3-openid

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
    - xylar
