{% set name = "python3-openid" %}
{% set version = "3.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33fbf6928f401e0b790151ed2b5290b02545e8775f982485205a066f874aaeaf

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - defusedxml

test:
  imports:
    - openid
    - openid.consumer
    - openid.extensions
    - openid.extensions.draft
    - openid.server
    - openid.store
    - openid.yadis
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://github.com/necaris/python3-openid
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: OpenID support for modern servers and consumers.
  dev_url: http://github.com/necaris/python3-openid

extra:
  recipe-maintainers:
    - carlodri
    - xylar
    
